export { default as Navigation } from "./Navigation";
export { default as footer } from "./footer";
export { default as Login } from "./login";
export { default as MutualFunds } from "./mutual-funds";
export { default as Stocks } from "./stocks";
export {default as Deposits} from "./deposits";
export {default as UsStocks} from "./us-stocks";
export {default as Gold} from "./gold";
export {default as CustomChatbot} from "./customChatbot";
export {default as Home} from "./home";